# Generated by Django 3.2.7 on 2021-10-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gameinstance_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinstance',
            name='result',
        ),
        migrations.AddField(
            model_name='result',
            name='gameinstance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.gameinstance'),
        ),
    ]
