# Generated by Django 3.2.7 on 2021-09-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating_count',
            field=models.IntegerField(default=-1),
        ),
    ]
